export const ADD_USER_TO_STORE = 'STORE.ADDUSER';
export const ADD_USERS_TO_STORE = 'STORE.ADDUSERS';
export const LOGIN_USER = 'STORE.LOGIN';
export const LOGOUT_USER = 'STORE.LOGOUT';

export const ADD_TOKEN_TO_STORE = 'STORE.ADDTOKENS';
export const ADD_PICURL_TO_STORE = 'STORE.ADDPICURL';

export const ADD_VACCINES_TO_STORE = 'STORE.ADDVACCINES';
export const ADD_HOSPITAL_TO_STORE = 'STORE.ADDHOSPITAL';
export const ADD_HOSPITALS_TO_STORE = 'STORE.ADDHOSPITALS';
export const ADD_HOSPITAL_VACCINES_TO_STORE = 'STORE.ADDHOSPITALVACCINES';

export const ADD_APPOINTMENT = 'STORE.ADDAPPOINTMENT';
export const GET_APPOINTMENTS = 'STORE.GETAPPOINTMENTS';
export const REJECT_APPOINTMENT = 'STORE.REJECTAPPOINTMENT';
export const APPROVE_APPOINTMENT = 'STORE.APPROVEAPPOINTMENT';
